
# ATTENTION DEVELOPER:
#
# When this service is ready to be built and deployed along with the other microservices, the following must occur
#
# 1. Rename this file to "homes-ms-retail.yml"
# 2. Remove this comment block.
# 3. Add the file to the ssp-configuration-repo Git repository under the "ms" branch.
# 4. Start this service to confirm it obtains its configuration.
#

management.security.enabled: false
security.basic.enabled: false

server:
  port: 9999
  contextPath: /homes/retail/v1

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sspms?autoReconnect=true&tinyInt1isBit=false&useSSL=false&zeroDateTimeBehavior=convertToNull
    username: root
    password: 'password'
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: validate

---
spring:
  profiles: dev


